#!/usr/bin/env bash

set -e

pip install -r requirements.txt

jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable rise --py --sys-prefix

echo "Run with: `jupyter notebook`"
